import { FC } from "react";
import ImageHolder from "../common/ImageHolder";
import { ButtonNext } from "pure-react-carousel";

interface ArticleSummaryHolderProps {
  source: string | null;
  summary: string;
  generatedByAi: boolean;
  articleUrl: string;
}

const ArticleSummaryHolder: FC<ArticleSummaryHolderProps> = ({
  source,
  summary,
  generatedByAi,
  articleUrl,
}) => {
  return (
    <div className="p-4">
      <div className="text-lg text-[#ecd9cb]">Article Summary</div>
      {/* Summary holder */}
      <div
        className={`bg-[#212121] border px-6 py-4 rounded text-base/loose text-justify first-letter:capitalize my-4 ${
          generatedByAi ? "border-[#ecd9cb]" : "border-red-500"
        }`}
      >
        {summary}

        <div className="text-xs/loose mt-8 mb-2 text-[#ecd9cb] flex flex-col gap-1 md:flex-row md:gap-0 md:items-center md:justify-between">
          {generatedByAi ? (
            <div>Generated by AI</div>
          ) : (
            <div>AI summarization not available!</div>
          )}
          {/* If the summary has not been generated by AI, then it is evident that it is a custom message that is sent when the summary is not available in DB, and so the source won't be shown */}
          {generatedByAi && source && (
            <div
              className={`text-white truncate md:max-w-[28rem] ${
                generatedByAi ? "" : "m-auto mr-0"
              }`}
            >
              Article source: {source}
            </div>
          )}
        </div>
      </div>
      {/* Info block */}
      <div className="flex flex-col gap-2 text-base/loose my-4 lg:my-6 border-l border-[#ecd9cb] w-fit px-4 py-1">
        {/* Read full article text block */}
        <div>
          <span>
            {generatedByAi
              ? "Want to know more? Click on"
              : "But don't worry, we got you! Click on"}
          </span>
          <div className="inline mx-1.5">
            <div className="inline-block align-middle">
              <ImageHolder
                heightAndWidthClasses="h-4 w-4"
                src="/images/svg/link-cream.svg"
                alt="link cream icon"
                priority={true}
                showLoading
              />
            </div>
          </div>
          <span>in the bottom navigation bar to read the full article!</span>
        </div>
        {/* Check out article details text block */}
        <div>
          <span>Click on</span>
          <ButtonNext>
            <span className="inline mx-1.5 text-sm uppercase text-[#ecd9cb] underline decoration-dotted underline-offset-4">
              Details
            </span>
          </ButtonNext>
          <span>to view details of the article.</span>
        </div>
      </div>
    </div>
  );
};

export default ArticleSummaryHolder;
