import Image from "next/image";
import { FC } from "react";

interface ArticleSummaryHolderProps {
  summary: string;
  articleUrl: string;
}

const ArticleSummaryHolder: FC<ArticleSummaryHolderProps> = ({
  summary,
  articleUrl,
}) => {
  return (
    <div className="p-4">
      <div className="text-lg text-[#ecd9cb]">Article Summary</div>
      {/* Summary holder */}
      <div className="bg-[#212121] border border-[#ecd9cb] px-6 py-4 rounded text-base/loose my-4">
        {summary}
        <div className="text-xs mt-6 mb-2 text-[#ecd9cb]">Generated by AI</div>
      </div>
      {/* Link to read full article */}
      <div className="text-base/loose mt-4 lg:mt-6 border-l border-[#ecd9cb] w-fit px-4 py-1">
        <span>Want to know more?</span>
        <a
          href={articleUrl}
          tabIndex={-1}
          className="hidden lg:inline text-[#ecd9cb] mx-2 border border-[#ecd9cb] p-2 rounded hover:bg-[#ecd9cb] hover:text-black"
          target="_blank"
          rel="noopener noreferrer"
        >
          Click here
        </a>
        <a
          href={articleUrl}
          tabIndex={-1}
          className="lg:hidden text-[#ecd9cb] mx-1 no-underline hover:underline"
          target="_blank"
          rel="noopener noreferrer"
        >
          Click here
        </a>
        <span>to read the full article!</span>
      </div>
      {/* Check out article details text block */}
      <div className="text-base/loose mb-4 lg:mb-6 border-l border-[#ecd9cb] w-fit px-4 py-1">
        <span>Click on</span>
        <div className="inline-block mx-2">
          <span className="text-sm uppercase text-[#ecd9cb]">Details</span>
          <div className="inline-block relative h-4 w-4 align-middle ml-2">
            <Image
              src="/images/svg/right-arrow-cream.svg"
              alt="right arrow cream icon"
              fill={true}
              priority
            />
          </div>
        </div>
        <span>to check out few details about the article.</span>
      </div>
    </div>
  );
};

export default ArticleSummaryHolder;
